### ISSUE TITLE
Design and Functions breaks when enabled

### ISSUE THREAD

**Issue by oneala** [eddiewebb/flarum-affiliator#1]
Hey, 

For some reason my Asirem theme and also some extensions and functionalities doesn't work anymore when enabled, any idea what could be ?

So, it goes from this https://i.gyazo.com/620e25ad6dd2d5f47c27b45b8ac3f888.png to this https://i.gyazo.com/effa13cbb32d8e976c3ed0aec25330e0.png 

link: forum.madcharge.com

thank you!

**Comment by eddiewebb** [comment]
0.0.3 might fix this.  If not please share your configuration

**Comment by oneala** [comment]
> 

I have the same problem :( what configuration should i share with you, what do you need? thank you!

**Comment by oneala** [comment]
> 0.0.3 might fix this. If not please share your configuration

have you transpile all files ?

**Comment by justoverclockl** [comment]
i've made a pr with transpiled file if you want

**Comment by eddiewebb** [comment]
> > 0.0.3 might fix this. If not please share your configuration
> 
> have you transpile all files ?

Sorry the community submitted PR for 0.0.3 did not include transpiled code.

I have reverted that release and published 0.0.4 including production transpiled JS.

**Comment by oneala** [comment]
> > > 0.0.3 might fix this. If not please share your configuration
> > 
> > 
> > have you transpile all files ?
> 
> Sorry the community submitted PR for 0.0.3 did not include transpiled code.
> 
> I have reverted that release and published 0.0.4 including production transpiled JS.

I just upgraded it and now works, thank you very much for your support and this very useful extension.
